package gallery

import (
	"fmt"
	"html/template"
	"os"
	"path/filepath"
)

type siteData struct {
	Version, ImageRoot string
	Total, Failed      int
	Groups             []GroupManifest
}

func writeSite(output, target string, index IndexManifest) error {
	target, err := filepath.Abs(target)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	imageRoot, err := filepath.Rel(filepath.Dir(target), output)
	if err != nil {
		return err
	}
	data := siteData{Version: index.Version, ImageRoot: filepath.ToSlash(imageRoot)}
	for _, item := range index.Groups {
		var group GroupManifest
		if err := readJSON(filepath.Join(output, item.Name, "manifest.json"), &group); err != nil {
			return fmt.Errorf("read group %s for site: %w", item.Name, err)
		}
		data.Groups = append(data.Groups, group)
		data.Total += len(group.Cases)
		for _, result := range group.Cases {
			if !result.OK {
				data.Failed++
			}
		}
	}
	file, err := os.Create(target)
	if err != nil {
		return err
	}
	defer file.Close()
	return siteTemplate.Execute(file, data)
}

var siteTemplate = template.Must(template.New("gallery").Funcs(template.FuncMap{
	"stats": func(result Result) string {
		value := result.Format
		if result.Width != nil && result.Height != nil {
			value += fmt.Sprintf(" · %d×%d", *result.Width, *result.Height)
		}
		if result.Bytes != nil {
			value += fmt.Sprintf(" · %.0f kB", float64(*result.Bytes)/1024)
		}
		return value
	},
}).Parse(`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>makeitaquote — examples</title>
  <meta name="description" content="Every rendering option makeitaquote supports, as a picture.">
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header class="page-head">
    <h1>makeitaquote</h1>
    <p class="tagline">Every rendering option, generated by the pure Go renderer.</p>
    <nav class="links"><a href="https://github.com/tikipiya/MiQ">GitHub</a><a href="https://pkg.go.dev/github.com/tikipiya/MiQ">Go package</a><a href="https://github.com/tikipiya/MiQ#readme">Docs</a></nav>
    <p class="meta">v{{.Version}} · {{.Total}} examples{{if .Failed}} · {{.Failed}} failed{{end}}</p>
  </header>
  <nav class="group-nav" aria-label="Sections">{{range .Groups}}<a href="#{{.Name}}">{{.Title}}</a>{{end}}</nav>
  <main>{{range .Groups}}
    <section class="group" id="{{.Name}}">
      <h2>{{.Title}} <span class="count">({{len .Cases}})</span></h2>
      <div class="grid">{{range .Cases}}
        <figure class="card{{if not .OK}} bad{{end}}">
		  {{if .Error}}<div class="missing">did not render</div>{{else}}<img src="{{$.ImageRoot}}/{{.File}}" alt="{{.Name}}" loading="lazy" decoding="async">{{end}}
		  <figcaption><div class="name">{{.Name}}</div>{{with .Note}}<div class="note">{{.}}</div>{{end}}<div class="stats">{{stats .}}</div>{{with .Error}}<div class="error">{{.}}</div>{{end}}</figcaption>
        </figure>{{end}}
      </div>
    </section>{{end}}
  </main>
  <footer class="page-foot"><p>Emoji graphics by <a href="https://github.com/jdecked/twemoji">Twemoji</a> (CC-BY 4.0). Fonts from <a href="https://fonts.google.com">Google Fonts</a>.</p><p>Sample text is public-domain prose and neutral statements about this library.</p></footer>
</body>
</html>
`))
